compile:
	@echo ---------------------------
	make -C ../src/threads/
	@echo ---------------------------
	make -C ../src/userprog/

clean:
	@echo ---------------------------
	make -C ../src/threads/ clean
	@echo ---------------------------
	make -C ../src/userprog/ clean
